### ISSUE TITLE
Change vertical tab to collapsed fieldset

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/field_group#14]
On the Manage Fields page, with Field Group enabled, there's a vertical tab at the bottom where a description of fieldgroups and an option to clone them sits. It takes up a fair bit of vertical space, and you need to scroll past it to find the Save button when adding fields. Also, I don't think any other module (that I know of) uses vertical tabs on this page...

I personally have never used the Clone option, and I don't believe the description needs to be always visible (once you've read it, you've read it).

I'd like to therefore suggest changing the vertical tab into a collapsed (by default) fieldset. That would mean less vertical space for those who create lots of fields and have to continually scroll down to the Save button, but also that the description and clone options are still easily accessible as needed.

**Comment by ghost** [comment]
Added a PR that fixes this.

**Comment by herbdool** [comment]
I'm hesitant to change this. There may be other modules that also add vertical tabs here so it's neater if they're all the same UX. I can't recall exactly for BD but Display Suite in D7 also used vertical tabs.

**Comment by ghost** [comment]
Can we then change it to a fieldset if the tabs don't already exist, and leave it as tabs if they do? That seems to me to fix both scenarios...

**Comment by ghost** [comment]
@herbdool I've made a new PR that keeps the vertical tab if there are other vertical tabs present, and changes it to a collapsed fieldset if not. The only caveat is that this module needs to run after any other modules that might add vertical tabs to that form, so as to know whether they exist already or not. Other than that it works nicely in my testing.

**Comment by herbdool** [comment]
Wondering what others think of the idea. Maybe @jenlampton, @klonos, @laryn @olafgrabienski. I'm not sure if it is or not. I'd like to not do anything unexpected for users. Not to expand the scope but I'm wondering if this UI change would be good for all vertical tabs in core. That is, if there's just one tab turn it into a fieldset (or something like that).

Not sure how it would work with the dynamic descriptions on vertical tabs.

**Comment by jenlampton** [comment]
Vertical tabs have a specific meaning: Anything inside one can be safely ignored. 

This UX element was added specifically to make the node/add form less overwhelming, by providing a safe place to put options that need to exist, but most of the time do not need to be changed. 

The values of the settings within are visible on the tabs, via the dynamic descriptions, so that people do not need to click into each one to confirm that the content (in the case of the node/add form) will be created how they intend.

The settings that live inside a vertical tab should always have a default value (or have a value assigned automatically when the form is submitted). This value should be (presumably) correctly configured before arriving on the page with the vertical tab. 

All places in core where we use vertical tabs strictly follow this pattern, and for the best user experience, contrib should follow.

We should not alternate between a setting living in a vertical tab or not, since the answer to the following question should not change: "Can this setting be safely ignored, because its value has been previously defined?" 

From reading the thread above, it sounds like the only concern here is a visual need for space, in which case a vertical tab is not the right element to use.

There are a handful of Drupal 7 contrib modules that started using vertical tabs without fully understanding their intent (module filter is the worst offender). I wonder if the Display Suite module might also be using vertical tabs for it's own organizational purposes?

When I port Drupal 7 contirb modules that abuse Vertical Tabs, I try to "fix them" by removing the vertical tabs. Once the tabs have been restored to fieldsets, I then try to determine what problem they were being used to solve, and see if it can't be solved in a way that creates a more consistent user experience :)

**In this case, I would vote to remove the vertical tab completely.**

We don't (yet) have a version of Display Suite for Backdrop, but when we get one we should also consider removing its vertical tabs, and addressing the problems they were being used to solve in another way.

edit: I'd also like to add that it's these kinds of subtle improvements (that perhaps aren't even noticed by most people) that make Backdrop a more enjoyable product to use :)

**Comment by herbdool** [comment]
Thanks for the full explanation @jenlampton! Makes me think we need a UX component guide for devs if there isn't one already. I didn't know this about vertical tabs.

So consensus is drifting towards removing vertical tabs altogether from the field page. I'll wait for a bit more feedback.

**Comment by jenlampton** [comment]
We started the [Human Interface Guidelines](http://backdrop-ops.github.io/backdrop-hig/) project back in 2014 (https://github.com/backdrop-ops/backdrop-hig) but it's never really gotten off the ground. I think vertical tabs might have even been the reason we decided we needed one, because they are so often misunderstood.

**Comment by herbdool** [comment]
I posted an issue in DS to see about coordinating an alternative https://github.com/backdrop-contrib/ds/issues/10.

**Comment by hosef** [comment]
> Vertical tabs have a specific meaning: Anything inside one can be safely ignored.

Is that documented anywhere? I never assume settings can be safely ignored unless I know what they do. The organizational structure is irrelevant to that. 

If we do need to conserve vertical space, what is the recommended option?
